### ISSUE TITLE
Installed wine runner isn't detected

### ISSUE THREAD

**Issue by sannagy90** [Vysp3r/ProtonPlus#114] opened 2023-05-26 18:30 UTC
I am using the flatpak version of Lutris and have `lutris-ge-lol-8.7-1-x86_64` installed. ProtonPlus doesn't seem to detect that it's installed already.

![image](https://github.com/Vysp3r/ProtonPlus/assets/51812249/e904d422-72e4-4a06-9601-60a0b1fcbd2e)

**Comment by Vysp3r** [comment] 2023-05-28 01:04
It works for the non LOL version of the runner. The problem is I based my search function using the normal version and did not make exceptions for the LOL version. I`ll make sure to add that fix in the upcoming release. Thank you for reporting this issue :)

**Comment by Vysp3r** [comment] 2023-05-28 13:43
I've fixed it in the dev branch. I'll keep this open until I push the update.

**Comment by Vysp3r** [comment] 2023-06-06 02:05
I pushed the fix. I will now close this issue. If it still persist, just open it back.

**Closed by Vysp3r** 2023-06-06 02:05 UTC
