### ISSUE TITLE
[BUG]When compatibilitytools.d is not in the launcher folder. Protonplus can not detect the launcher.

### ISSUE THREAD

**Issue by neovali** [Vysp3r/ProtonPlus#65] opened 2023-01-12 11:53 UTC
**Describe the bug**
When compatibilitytools. d is not in the steam folder. ProtonPlus can not detect the launcher.

**To Reproduce**
1. Open Protonplus and found nothing in the Launcher column.
2. ```mkdir -p ~/.local/share/Steam/compatibilitytools.d```
3. It appeared

**Desktop**
 - OS: Fedora 37
 - DE: GNOME 42
 - Type: Flatpak from flathub

**Comment by Vysp3r** [comment] 2023-01-12 19:56
That's weird, it was working before, and I never touched that part. I'll check that this weekend!

**Comment by NEOVALI** [comment] 2023-01-13 05:03
@Vysp3r  
[录屏 2023-01-13 13-02-06.webm](https://user-images.githubusercontent.com/85693457/212241502-1bf862de-ff3f-4213-8d09-6f8e60c5a7db.webm)

**Comment by Vysp3r** [comment] 2023-01-18 13:59
I forgot about it last weekend ahah. I will try to fix that for the upcoming one.

**Comment by Vysp3r** [comment] 2023-01-21 23:10
Would you be able to test the branch from this issue and tell me if that works any better for you?

**Comment by NEOVALI** [comment] 2023-01-22 02:31
> Would you be able to test the branch from this issue and tell me if that works any better for you?

I'm sorry I'm celebrating Chinese New Year with my family in my hometown, and I don't have a computer now.

**Comment by NEOVALI** [comment] 2023-01-28 03:32
@Vysp3r https://github.com/Vysp3r/ProtonPlus/tree/65-bugwhen-compatibilitytools-d-is-not-in-the-launcher-folder-protonplus-can-not-detect-the-launcher 

checked, work fine.

**Comment by Vysp3r** [comment] 2023-01-28 03:33
Alright, I'll make an update this weekend with the fix.

**Comment by Vysp3r** [comment] 2023-01-28 15:42
Fixed in https://github.com/Vysp3r/ProtonPlus/commit/8fd5858fe9bd8b04e9ae81009ee88bad78c8c828.

**Comment by Vysp3r** [comment] 2023-01-28 15:42
It helped me fixed another problem with Flatpak permissions too, so thank you!

**Comment by Linwer** [comment] 2023-02-12 14:11
still getting this as of v0.3.6

**Comment by Vysp3r** [comment] 2023-02-12 15:03
> still getting this as of v0.3.6

I'll need information about your system please.

**Comment by neovali** [comment] 2023-02-12 17:31
work well on normal installed steam.
but not work well on flatpak version steam

**Comment by Vysp3r** [comment] 2023-02-12 18:11
Alright, I'll check on my end if I can reproduce in a few.

**Comment by Vysp3r** [comment] 2023-02-12 21:32
The thing is that it works for me and I really don't know what could be the problem on your end.

**Comment by Vysp3r** [comment] 2023-02-12 21:33
Permission for flatpak are okay and if the directory creations work for the normal steam install it means it's not the function that creates the folder that is the problem. So I'm lost here.

**Comment by Vysp3r** [comment] 2023-02-12 21:34
Could you guys maybe try to add permission to ProtonPlus so it has access to all of your home folder just to ensure it's not a permission problem?

**Comment by neovali** [comment] 2023-02-12 22:41
[bug-protonplus 2023-02-13 06-38-37.webm](https://user-images.githubusercontent.com/85693457/218341636-5dbf1568-dd48-4bd7-9631-2f9ddc70b406.webm)

**Comment by neovali** [comment] 2023-02-13 03:29
flatpak version protonplus
flatpak version steam

OS: Fedora Silverblue 37 
DE: GNOME 42

**Comment by Vysp3r** [comment] 2023-02-13 03:42
I'll check tomorrow, it's getting and I did not finding anything for now.

**Comment by milomc123** [comment] 2023-02-21 17:56
The flatpak permissions don't appear to be fixed. On a fresh install the app only has access to `~/.var/app/com.valvesoftware.Steam/data/Steam/compatibilitytools.d` instead of `~/.var/app/com.valvesoftware.Steam/data/Steam`, which causes this bug.

Output of `flatpak info --show-permissions com.vysp3r.ProtonPlus` on ProtonPlus version 0.3.7:
```
[Context]
shared=network;ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=~/.steam/root/compatibilitytools.d;~/.local/share/bottles/runners;~/.var/app/net.lutris.Lutris/data/lutris;~/.local/share/Steam/compatibilitytools.d;~/.var/app/com.valvesoftware.Steam/data/Steam/compatibilitytools.d;xdg-run/gvfsd;~/.var/app/com.heroicgameslauncher.hgl/config/heroic/tools;~/.local/share/lutris;~/.var/app/com.usebottles.bottles/data/bottles/runners;~/.config/heroic/tools;

[Session Bus Policy]
org.gtk.vfs.*=talk
```
This can be quickly resolved by running `flatpak override`:
```
sudo flatpak override com.vysp3r.ProtonPlus --filesystem="~/.var/app/com.valvesoftware.Steam/data/Steam"
```

It appears that the [flatpak manifest available on flathub](https://github.com/flathub/com.vysp3r.ProtonPlus/blob/master/com.vysp3r.ProtonPlus.json), is not up to date with the [one in this repo](https://github.com/Vysp3r/ProtonPlus/blob/main/com.vysp3r.ProtonPlus.json).

**Comment by Vysp3r** [comment] 2023-02-21 23:14
That's weird, I thought I fixed that. Maybe I forgot something somewhere. I'll look into that right now. Thanks for the input @milomc123!

**Comment by Vysp3r** [comment] 2023-02-22 01:06
Fixed the manifest in https://github.com/flathub/com.vysp3r.ProtonPlus/pull/14/files. I will be closing this issue, but if it still persist, tell me and I will reopen it.

**Closed by Vysp3r** 2023-02-22 01:06 UTC
Labels: bug
