### ISSUE TITLE
[BUG] Visual Problems with v0.4.7

### ISSUE THREAD

**Issue by felixawesomeokeefe** [Vysp3r/ProtonPlus#158] opened 2023-11-16 20:37 UTC
**Describe the bug**
In the application GUI window all text is wrapped to very narrow lines (12 characters).

**To Reproduce**
Open the application. This happens since update to the current version. v0.4.7

**Expected behavior**
Text should be displayed making use of the width of the GUI window.

**Screenshots**
![Screenshot_20231116_213200](https://github.com/Vysp3r/ProtonPlus/assets/8710248/c302b447-0787-4199-8ccf-20e6033e5ec9)

**Desktop (please complete the following information):**
 - OS: 6.6.1-1-MANJARO
 - DE: KDE Plasma 5.72.9 (Wayland)
 - Type: Flatpak

*Additional context*
Additionally all the text characters used in the GUI have no rounded edges making them appear rough and pixelated.

*EDIT:
I forgot to mention i'm using the Manjaro unstable branch.
I've just tried uninstalling and reinstalling ProtonPlus using Discover (Flatplak completely disappeared from pamac since running updates yesterday). No change to the above reported behavior.

**Comment by Vysp3r** [comment] 2023-11-17 18:04
I tried on a few of my devices and I cannot reproduce any of that. I'll try to download manjaro in a VM using your specs this weekend.

**Comment by sergiotca** [comment] 2023-11-21 01:28
I'm not able to replicate OP specific issues either. But I  am seeing the Bottles icon missing too (left menu):
![image](https://github.com/Vysp3r/ProtonPlus/assets/41351896/1d762a43-9001-4a88-bf6a-1c41b0be527b)

Is this by design, or is it a visual issue?

Fedora 38 & Gnome 44.6 & ProtonPlus v0.4.7 (Flatpak)

**Comment by Vysp3r** [comment] 2023-11-21 04:38
@sergiotca This is not supposed to be like that. I will push a fix for that tomorrow.

**Comment by felixawesomeokeefe** [comment] 2023-11-21 19:18
I forgot to mention i'm using the Manjaro unstable branch.
I've just tried uninstalling and reinstalling ProtonPlus using Discover. No change to the above reported behavior. As Flatplak completely disappeared from pamac since running updates yesterday.

**Comment by Vysp3r** [comment] 2023-11-22 17:44
@sergiotca I didn't have time to fix the icon last night, but I will have time this weekend for sure.

**Comment by sergiotca** [comment] 2023-11-22 18:15
> @sergiotca I didn't have time to fix the icon last night, but I will have time this weekend for sure.

Whenever you get the chance friend. I appreciate your work.

**Comment by felixawesomeokeefe** [comment] 2023-11-22 20:30
I think I found the issue. It seems to have something to do with Wayland. I logged out and switched session from Plasma Wayland to Plasma X11 and ProtonPlus displays normally. Also screen fonts are nice and smooth in the app which they weren't in Wayland.

**Comment by Vysp3r** [comment] 2023-11-23 15:14
@felixawesomeokeefe Oh then it must be something with GTK/Adwaita. I will go on their Matrix and link this issue for them to maybe get a look at the problem.

**Comment by Vysp3r** [comment] 2023-11-23 18:06
Since the problem is not related to something on my end, I will now close this issue. Regarding the icon problem for Bottles, it was fixed in https://github.com/Vysp3r/ProtonPlus/pull/159.

**Closed by Vysp3r** 2023-11-23 18:06 UTC
Labels: bug
