### ISSUE TITLE
[BUG]Critical error. The application crashes during startup

### ISSUE THREAD

**Issue by smotim** [Vysp3r/ProtonPlus#37] opened 2022-12-12 06:14 UTC
**Describe the bug**
```
(protonplus:2): GLib-GIO-CRITICAL **: 11:07:49.627: g_list_store_append: assertion 'g_type_is_a (G_OBJECT_TYPE (item), store->item_type)' failed

(protonplus:2): GLib-GObject-WARNING **: 11:07:49.629: ../gobject/gtype.c:3210: invalid class pointer '0x562198f23be0'
```
The same problem exists when I build an application in Builder myself

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - DE: GNOME 43
 - Type: source and Flatpak

**Comment by Vysp3r** [comment] 2022-12-12 13:20
Even the Flatpak version does that?

**Comment by smotim** [comment] 2022-12-12 13:27
At first, the flathub version did not start. Only then I tried to build the application myself. It doesn't work in both cases

**Comment by Vysp3r** [comment] 2022-12-12 13:29
Since I can't reproduce on my system your problem would you be inclined to use the debug feature of GNOME Builder so we can pin point the cause of the problem?

**Comment by smotim** [comment] 2022-12-12 13:29
Yes, I can

**Comment by Vysp3r** [comment] 2022-12-12 13:30
I think I know which part may be the problem, but just to make sure I will give you a few break points to place and you just have to tell me if you can reach them.

**Comment by smotim** [comment] 2022-12-12 13:32
Okay, I'm waiting

**Comment by Vysp3r** [comment] 2022-12-12 13:42
Can it reach /src/Windows/Home.vala line 78?
Can it reach /src/Views/Tools.vala line 108?

**Comment by smotim** [comment] 2022-12-12 13:48
![изображение](https://user-images.githubusercontent.com/57951811/207061327-2207fa65-8b8b-4435-a157-3305c85039da.png)
Did you do it right?

**Comment by Vysp3r** [comment] 2022-12-12 13:52
I mean it's suppose to land one of the two lines I gave you.

**Comment by Vysp3r** [comment] 2022-12-12 13:52
Does the application crash after continuing that line?

**Comment by smotim** [comment] 2022-12-12 13:56
![изображение](https://user-images.githubusercontent.com/57951811/207062921-bba4c345-f2d7-4593-9e44-fa67b05a54eb.png)
When I select one or both breakpoints from below and run with the debugger, this IModel file opens. Do I need to do something else?

**Comment by Vysp3r** [comment] 2022-12-12 13:59
Oh yeah press the little Play button in the middle of the picture to continue debugging

**Comment by Vysp3r** [comment] 2022-12-12 14:01
If it does nothing it means it crashed before reaching the breakpoint. From what I'm reading in the console, it looks like it did crash otherwise I don't  know why it would stop there if you haven't put any breakpoint.

**Comment by smotim** [comment] 2022-12-12 20:48
I tried installing Proton Plus with flathub on a VM. First I used Fedora 37, then Manjaro Gnome. And in both distributions, version 0.3.0 does not run. When running through the terminal, the same two errors appear that I gave at the beginning of the issue.

Maybe this information will help somehow

**Comment by Vysp3r** [comment] 2022-12-13 00:51
I don't understand how we can get different result, it's annoying

**Comment by Vysp3r** [comment] 2022-12-13 19:11
Can it reach /src/Views/Tools.vala line 100?

**Comment by smotim** [comment] 2022-12-13 20:56
Yes, it reaches in both cases.

**Comment by Vysp3r** [comment] 2022-12-13 21:02
Okay great, now I know which part isn't working!

**Comment by Vysp3r** [comment] 2022-12-13 21:03
Just to be extra sure, can it reach /src/Views/Tools.vala line 101?

**Comment by smotim** [comment] 2022-12-13 21:14
No, it does not reach 101 lines. The IModel file opens, as in the screenshot above. Looks like you're right

**Comment by Vysp3r** [comment] 2022-12-13 21:15
Alright, I'll look into that since we now know the source of the problem.

**Comment by im-viriv** [comment] 2022-12-13 22:31
i was about to make an issue but it seems this already being solved ^-^

**Comment by Vysp3r** [comment] 2022-12-13 23:01
Would you guys be able to tell me what's in /home/vysp3r/.var/app/com.vysp3r.ProtonPlus/config/preferences.json

**Comment by im-viriv** [comment] 2022-12-13 23:03
![image](https://user-images.githubusercontent.com/30769091/207463776-8e4664dc-0a36-4a4f-8482-400e002fcc38.png)
(i'm on silverblue btw but i guess we already established that)

**Comment by im-viriv** [comment] 2022-12-13 23:06
i'm using the flatpak version

**Comment by Vysp3r** [comment] 2022-12-13 23:07
imma go eat, I'll ask more question after

**Comment by Vysp3r** [comment] 2022-12-13 23:27
Where do Flatpak saves there stuff then if it's not in ~/.var

**Comment by im-viriv** [comment] 2022-12-13 23:31
mb, sorry for the trouble. i deleted the folder and reinstalled the flatpak. the config is now back and contains this:
```json
{
	"style" : "system",
	"rememberLastLauncher" : true,
	"lastLauncher" : ""
}```

**Comment by Vysp3r** [comment] 2022-12-13 23:56
Why do you have ```

**Comment by im-viriv** [comment] 2022-12-14 00:08
That was just for entering the visual code block mode which enables syntax highlighting and keeps tabs and spacing and such

**Comment by Vysp3r** [comment] 2022-12-14 00:31
Can it reach /src/Models/Launcher.vala line 55?

**Comment by smotim** [comment] 2022-12-14 03:57
![изображение](https://user-images.githubusercontent.com/57951811/207501479-ad21b6cc-2ca7-4f61-a9b1-961c80d68cb4.png)
for some reason, a breakpoint is not set at 55. At first it looks like in the screenshot, and after starting the debugger, I just have nothing in the "breakpoints" section
it reaches 62.

**Comment by smotim** [comment] 2022-12-14 03:58
```
{
	"style" : "system",
	"rememberLastLauncher" : true,
	"lastLauncher" : ""
}
```
it's in preferences.json

**Comment by Vysp3r** [comment] 2022-12-14 18:14
It does not make sense that it reaches line 62 in Launcher.vala, but does not reach 101  in Tools.vala. Can you test again to make sure it does not reach /src/Views/Tools.vala line 101?

**Comment by smotim** [comment] 2022-12-14 18:40
> And could you tell me if you put a break point at line 63 in /src/Models/Launcher.vala what does the value of test equals? Use the branch from this issue for that. https://github.com/Vysp3r/ProtonPlus/tree/37-bugcritical-error-the-application-crashes-during-startup ![image](https://user-images.githubusercontent.com/62019735/207674778-2b282eac-1695-43ef-8ae3-7873dbc5d530.png)

![изображение](https://user-images.githubusercontent.com/57951811/207683414-1ad13b30-2179-4d46-980d-4a25e3b356a1.png)
Is this what I needed to see?

**Comment by smotim** [comment] 2022-12-14 18:45
![изображение](https://user-images.githubusercontent.com/57951811/207684978-70db3bd5-ffea-4482-9492-3ca33834d225.png)
![изображение](https://user-images.githubusercontent.com/57951811/207685034-ef030ecd-089c-457a-a194-648df064c369.png)
Does not reach 62 and 101

**Comment by Vysp3r** [comment] 2022-12-14 19:53
Ain't gonna lie I'm a bit lost on why that happens.

**Comment by Vysp3r** [comment] 2022-12-14 19:54
The part where it crashes is a simple one and should not in any way crash like that.

**Comment by Vysp3r** [comment] 2022-12-14 19:56
> > And could you tell me if you put a break point at line 63 in /src/Models/Launcher.vala what does the value of test equals? Use the branch from this issue for that. https://github.com/Vysp3r/ProtonPlus/tree/37-bugcritical-error-the-application-crashes-during-startup ![image](https://user-images.githubusercontent.com/62019735/207674778-2b282eac-1695-43ef-8ae3-7873dbc5d530.png)
> 
> ![изображение](https://user-images.githubusercontent.com/57951811/207683414-1ad13b30-2179-4d46-980d-4a25e3b356a1.png) Is this what I needed to see?

Oh shit I think I found it. Look at the value of launchers in the pic you sent me. It says error blablabla.

**Comment by Vysp3r** [comment] 2022-12-14 19:57
Could you send me the full text because I can't read it all in your pic.

**Comment by Vysp3r** [comment] 2022-12-14 19:58
![image](https://user-images.githubusercontent.com/62019735/207701534-67c716a7-e562-4949-a6a0-e4e7ba41a573.png)
Here's mine for reference.

**Comment by smotim** [comment] 2022-12-14 20:01
![изображение](https://user-images.githubusercontent.com/57951811/207702199-41960b37-65ea-4012-af27-f6bdcd42dad3.png)
I don't know how to copy it. sorry about the picture

**Comment by Vysp3r** [comment] 2022-12-14 20:17
No worries I just wanted to see the full thing.

**Comment by Vysp3r** [comment] 2022-12-14 20:43
Can you test the branch I sent you. I added a possible fix.

**Comment by smotim** [comment] 2022-12-14 20:47
![изображение](https://user-images.githubusercontent.com/57951811/207710429-3b0d0855-b1a9-4fe0-9aaa-404ec9902a90.png)
I did a git pull and launched, it seems everything remained the same.  The value has not changed.

**Comment by smotim** [comment] 2022-12-14 20:51
We have very different time zones, so I have to go to bed soon. If you can come up with something, I'll look at it in 10 hours.

**Comment by smotim** [comment] 2022-12-14 21:05
Yes. The app is working now!

**Comment by smotim** [comment] 2022-12-14 21:07
![изображение](https://user-images.githubusercontent.com/57951811/207713889-c2995970-9cfd-4c82-ac13-08c43326381e.png)
But. Folders from the home directory are now visible in the list.

**Comment by Vysp3r** [comment] 2022-12-14 21:10
What the heck. There must be something wrong with the permissions then.

**Comment by Vysp3r** [comment] 2022-12-14 21:15
Tell me if the crash still happens in 0.3.1 then. It should be available on Flatpak or else build from source from the main branch.

**Comment by przmkg** [comment] 2022-12-14 23:05
I still have the same crash with 0.3.1 (Flatpak).

```
(protonplus:2): GLib-GIO-CRITICAL **: 00:03:30.587: g_list_store_append: assertion 'g_type_is_a (G_OBJECT_TYPE (item), store->item_type)' failed

(protonplus:2): GLib-GObject-WARNING **: 00:03:30.589: ../gobject/gtype.c:3210: invalid class pointer '0x55ecaf7f6b80'
```

**Comment by Vysp3r** [comment] 2022-12-15 00:08
You can now test the branch associated with this issue. I've tried something that may fix this issue.

**Comment by wehagy** [comment] 2022-12-15 05:32
Created a clean Fedora 37 virtual machine and my daily drivers Fedora 37, Debian testing/bookworm and Manjaro, still have the same crash with 0.3.1 (Flatpak).

```
~$ flatpak run com.vysp3r.ProtonPlus 

(protonplus:2): GLib-GIO-CRITICAL **: 23:51:27.389: g_list_store_append: assertion 'g_type_is_a (G_OBJECT_TYPE (item), store->item_type)' failed

(protonplus:2): GLib-GObject-WARNING **: 23:51:27.391: ../gobject/gtype.c:3210: invalid class pointer '0x556313c1ec20'
```

Builded the branch associated with this issue using flatpak builder, and now it work on the Fedora 37 virtual machine and all my daily drivers.

But the *.tar.gz file don't auto prune and I can't delete the compatibility tool if I click to delete.

```
~$ flatpak run com.vysp3r.ProtonPlus
Trash portal failed on /home/wgimenes/.var/app/com.vysp3r.ProtonPlus/config/preferences.json
Error opening file “/home/wgimenes/.var/app/com.vysp3r.ProtonPlus/config/preferences.json”: File exists
Trash portal failed on /home/wgimenes/.var/app/com.valvesoftware.Steam/data/Steam/compatibilitytools.d/GE-Proton7-42.tar.gz
Trash portal failed on /home/wgimenes/.var/app/com.valvesoftware.Steam/data/Steam/compatibilitytools.d/GE-Proton7-42
```

```
~/.var/app/com.valvesoftware.Steam/data/Steam/compatibilitytools.d$ ls -l
total 405004
drwxrwxr-x 1 wgimenes wgimenes       306 dez  2 20:22 GE-Proton7-42
-rw-r--r-- 1 wgimenes wgimenes 414720148 dez  2 21:14 GE-Proton7-42.tar.gz
```

**Comment by smotim** [comment] 2022-12-15 08:08
> You can now test the branch associated with this issue. I've tried something that may fix this issue.

The application starts, the list is fixed. For some reason, the Proton installation has been hanging for several minutes at the "loading" stage with zero progress. No errors seem to be output to the terminal. I mean, it looks like the download doesn't start at all


By the way, unlike @wehagy, I have no problem removing compatibility tools

**Comment by Vysp3r** [comment] 2022-12-15 19:36
Does your problem happens for every launcher or only a specific one?

**Comment by Vysp3r** [comment] 2022-12-15 19:40
@wehagy do you happen to have 'GTK_USE_PORTAL=1' in your /etc/environment?

**Comment by smotim** [comment] 2022-12-15 19:42
> Does your problem happens for every launcher or only a specific one? @smotim

every

**Comment by Vysp3r** [comment] 2022-12-15 19:44
@smotim would you send me a picture with the path of one of the launcher and verify that those path are correct too on your side. Like that:
![image](https://user-images.githubusercontent.com/62019735/207952433-528b8133-2f20-40a9-bd24-ccec3ee77d61.png)

**Comment by smotim** [comment] 2022-12-15 19:47
![изображение](https://user-images.githubusercontent.com/57951811/207952835-f8111621-50ea-4f74-9728-ce0f99eebea2.png)
I can. Maybe I explained it badly. That's where the problem comes in. It says "loading" and nothing happens for a long time.

**Comment by Vysp3r** [comment] 2022-12-15 19:48
But does something finally happen or it's just broken?

**Comment by smotim** [comment] 2022-12-15 19:52
![изображение](https://user-images.githubusercontent.com/57951811/207953446-017be72c-eb34-40d6-9c4e-2300875230ee.png)
Yes, it is being downloaded. I just translated it back from Russian incorrectly.:) As a result, nothing happens, that's why I wrote about it.

**Comment by Vysp3r** [comment] 2022-12-15 19:57
Does it extract the downloaded tool too?

**Comment by smotim** [comment] 2022-12-15 20:00
![изображение](https://user-images.githubusercontent.com/57951811/207955394-887548d4-e463-48c4-865e-9595f428db8d.png)
Is that what you mean?

**Comment by Vysp3r** [comment] 2022-12-15 20:01
When you click install, it firsts download a .tar.xz or something like that then it extract it to a folder with the tool name and version. My question is when you install a tool, does it shows up in a folder extracted.

**Comment by smotim** [comment] 2022-12-15 20:04
at what address should the extracted folder be located?  it seems that there are no folders with this name in the whole home.

**Comment by smotim** [comment] 2022-12-15 20:07
No, a new folder is not being created. These two are left over from the previous version (0.2.3)

**Comment by wehagy** [comment] 2022-12-16 01:10
> @wehagy do you happen to have 'GTK_USE_PORTAL=1' in your /etc/environment?

The file /etc/environment on my debian and manjaro systems are empty, tried to set up and the two systems freeze on logon.
Created a new issue https://github.com/Vysp3r/ProtonPlus/issues/43 to track this bug.

**Comment by Vysp3r** [comment] 2022-12-16 13:41
@smotim can you tell me the values of url and path when you put a breakpoint on /src/Utils/Web.vala line 20. Use the branch associated to this issue.

**Comment by smotim** [comment] 2022-12-16 15:27
> @smotim can you tell me the values of url and path when you put a breakpoint on /src/Utils/Web.vala line 20. Use the branch associated to this issue.
![изображение](https://user-images.githubusercontent.com/57951811/208131685-6860265d-aade-4e63-8bb9-1a629c7d2cbc.png)

**Comment by Vysp3r** [comment] 2022-12-16 15:41
Hmmmmm, the url and the path looks good.

**Comment by Vysp3r** [comment] 2022-12-16 19:04
Can it reach /src/Utils/Web.vala line 26?

**Comment by smotim** [comment] 2022-12-17 11:16
> Can it reach /src/Utils/Web.vala line 26?

Yes, it can reach

**Comment by Vysp3r** [comment] 2022-12-18 13:30
So the download starts, but it doesn't at the same time? Because if it can reach that, the download started. Do you see a file appear in the directory when you click install or just nothing at all?

**Comment by smotim** [comment] 2022-12-18 14:05
Nothing appears

**Comment by Vysp3r** [comment] 2022-12-18 14:17
Is the download working for anyone? @wehagy @im-viriv

**Comment by Vysp3r** [comment] 2022-12-18 14:19
I just really don't know anymore what could be the problem now. If it reaches the end of that function it should work. Otherwise there would be an error or something.

**Comment by im-viriv** [comment] 2022-12-18 15:39
> Is the download working for anyone? @wehagy @im-viriv 

Can i check in the public release? Or should I compile the branch?

**Comment by Vysp3r** [comment] 2022-12-18 15:57
You would have to compile the branch.

**Comment by wehagy** [comment] 2022-12-19 00:57
> Is the download working for anyone? @wehagy @im-viriv

Download and extraction is working for me.

**Comment by smotim** [comment] 2022-12-19 12:40
![изображение](https://user-images.githubusercontent.com/57951811/208428051-88f4d961-cde0-49d3-943e-7bb9e2fa30ea.png)
I just noticed this in the output of the application. This translates to 'Action not supported'. This message won't help you understand the source of the problem?

**Comment by Vysp3r** [comment] 2022-12-19 14:22
Could you tell me when that output shows up.

**Comment by smotim** [comment] 2022-12-19 16:28
Right at the moment of clicking on the "install" button. And how can I find out a specific line?

**Comment by Vysp3r** [comment] 2022-12-19 17:14
![image](https://user-images.githubusercontent.com/62019735/208481880-40ee13aa-4903-4ba0-9589-e731995b84ef.png)
Put a breakpoint in /src/Windows/Installer.vala line 94 and click on the button highlighted in the picture until the error message appears and tell me in what file and on what line it was.

**Comment by smotim** [comment] 2022-12-19 17:45
![изображение](https://user-images.githubusercontent.com/57951811/208487549-7617221c-bd33-4c45-b543-d557e8027f82.png)
It seems like this. Did I take the right screenshot?

**Comment by smotim** [comment] 2022-12-19 17:46
![изображение](https://user-images.githubusercontent.com/57951811/208487767-0d8ca7a7-922b-47f0-9ef9-fe8e7fd9051e.png)
I pressed this button. The message "Action is not supported" appeared at the same moment when this empty file was opened

**Comment by smotim** [comment] 2022-12-19 17:48
after 96 lines, this file opens instead of going to 97

**Comment by Vysp3r** [comment] 2022-12-19 20:51
So your computer doesn't support the Timeout function from what I can see.

**Comment by Vysp3r** [comment] 2022-12-19 20:54
It's impossible that your computer can't enter the Timeout, it's supposed to work on every computer.

**Comment by Vysp3r** [comment] 2022-12-19 20:55
It must be something else again, but what is the question. I really don't know anymore.

**Comment by smotim** [comment] 2022-12-19 20:59
Yeah. And up to 0.3.0 version everything worked fine. I will use proton qt up for now. Maybe it will also be repaired by accident? :)
Thank you for spending so much time on my problem

**Comment by Vysp3r** [comment] 2022-12-19 21:06
So 0.3.0 works but not up? Or everything under 0.3.0?

**Comment by Vysp3r** [comment] 2022-12-19 21:11
Because if so I can check the difference between the latest working version for you and the latest and check what may have messed up ProtonPlus on your end.

**Comment by smotim** [comment] 2022-12-19 21:12
I created the last issue when I used the 0.2.0 version. Everything worked well in it, except what I wrote about in the issue. And in versions 3.0 and 3.1 there are new errors from this issue

**Comment by Vysp3r** [comment] 2022-12-19 21:13
Alright that may help then. I'll give that a try.

**Comment by smotim** [comment] 2022-12-19 21:14
previously, there were only minor problems with the frontend. since version 3.0, there have been problems with the basic functionality.

**Comment by Vysp3r** [comment] 2022-12-19 21:14
I'll try again to find the problem :)

**Comment by Vysp3r** [comment] 2022-12-19 22:04
@smotim Does that works for you? https://github.com/Vysp3r/ProtonPlus/tree/1bc62b80bc75f7cfe9ecaf37e0295931725d86be (You will have to build it)

**Comment by smotim** [comment] 2022-12-19 22:21
can you please tell me how to clone this branch? 'git clone -b <branch name> <repository>' worked for me before

**Comment by Vysp3r** [comment] 2022-12-19 23:00
Just download the zip file on the website, I dont really know how to clone from a tag.

**Comment by Vysp3r** [comment] 2022-12-19 23:00
https://github.com/Vysp3r/ProtonPlus/releases/tag/v0.2.3

**Comment by wehagy** [comment] 2022-12-20 00:47
You can just clone the repo and use `git checkout tags/<the tag you want to test>` in this case `git checkout tags/v0.2.3` to list tags use `git tag --list` or if you are using flatpak `flatpak update --commit=d9d848113996294c0713b0d32c107b1662ae148eeaf96b3764ea5761a8b3f530 com.vysp3r.ProtonPlus` and your app rollback to v0.2.3 from flathub, to list all versions and see commits `flatpak remote-info --log <repo name> <app name>`, to see ProtonPlus app history `flatpak remote-info --log flathub com.vysp3r.ProtonPlus`

**Comment by smotim** [comment] 2022-12-20 07:12
Thank you @wehagy . 
So, I rolled back to flatpak 0.2.3 and installing the tools works here. But before that, I tried to build different versions myself (from 0.2.0 to the current one). And for some reason, downloading didn't work in all these versions when I knocked them down on my own

**Comment by smotim** [comment] 2022-12-20 07:14
There, in builder, the same message appears "the action is not supported" in all versions that I built myself

**Comment by Vysp3r** [comment] 2022-12-20 13:22
I will try to move the download to libcurl to see if that's work for you.

**Comment by Vysp3r** [comment] 2022-12-20 14:22
I was able to download a file using libsoup3. I should have a test ready later today for you @smotim!

**Comment by Vysp3r** [comment] 2022-12-20 18:01
Would anyone that had the original problem of this issue be able to test the dev branch. I've modified a bit the fix and just want to confirm it is still working for you guys. https://github.com/Vysp3r/ProtonPlus/tree/dev

**Comment by smotim** [comment] 2022-12-20 18:05
Checked it out. The same errors returned, which are written about at the very beginning of the issue

**Comment by Vysp3r** [comment] 2022-12-20 18:10
Makes no fucking sense...

**Comment by Vysp3r** [comment] 2022-12-20 18:13
Okay now it's the exact same thing. Does it works?

**Comment by smotim** [comment] 2022-12-20 18:34
The application starts up again, these errors no longer appear. The download does not work as before

**Comment by Vysp3r** [comment] 2022-12-20 18:43
That I did not fix ahah

**Comment by Vysp3r** [comment] 2022-12-20 22:15
Since this issue is now fixed, I will close it. For your download problem, please create a new one. See https://github.com/Vysp3r/ProtonPlus/commit/edbe5ec36c0458502fa8719db9a95c43997d367c

**Closed** 2022-12-20 22:15 UTC
Labels: bug
