### ISSUE TITLE
[BUG] GE-Proton7-42 is displayed with the name "." when installed to Steam (Flatpak)

### ISSUE THREAD

**Issue by Newbytee** [Vysp3r/ProtonPlus#33] opened 2022-12-08 09:15 UTC
**Describe the bug**
After installing GE-Proton7-42 to Steam (Flatpak), the tool only shows up as "." in the ProtonPlus GUI. I think it had a blank name before I restarted ProtonPlus, but I'm not 100% sure about this.

**To Reproduce**
1. Install GE-Proton7-42 to Steam (Flatpak)
2. Observe that the tool has a blank name
3. Restart ProtonPlus
4. Observe that the tool now is called "."

**Expected behavior**
Presumably the actual name of the tool should show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/4428753/206406196-a1cc2d1b-180f-4aa5-af1a-f3d31f9a26a9.png)

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - DE: GNOME 43
 - Type: Flatpak from Flathub

**Comment by Vysp3r** [comment] 2022-12-08 12:51
Would you be able to tell me what's in this directory?
`/home/dev/.var/app/com.valvesoftware.Steam/.steam/steam/compatibilitytools.d/`

**Comment by Newbytee** [comment] 2022-12-09 21:32
Here you go:
```
$ ls ~/.var/app/com.valvesoftware.Steam/.steam/steam/compatibilitytools.d/
GE-Proton7-42
```

**Comment by Vysp3r** [comment] 2022-12-11 16:48
I will try to fix that for v0.3.1, but since I cannot reproduce on a vanilla VM of Fedora 37 and on my machine it may take time.

**Comment by yochananmarqos** [comment] 2022-12-11 19:05
I can reproduce this with my `protonplus` AUR package.

**Comment by Vysp3r** [comment] 2022-12-11 23:16
Is it only doing that with Steam (Flatpak) for both of you?

**Comment by yochananmarqos** [comment] 2022-12-11 23:27
@Vysp3r I didn't test the Flatpak. I'm building from source with Meson with my AUR package.

**Comment by Vysp3r** [comment] 2022-12-11 23:30
I meant like does this happen with every launcher or only Steam (Flatpak)

**Comment by yochananmarqos** [comment] 2022-12-11 23:35
Lutris and Lutris DXVK display the installed version correctly.

**Comment by Vysp3r** [comment] 2022-12-11 23:48
Alright, I'll check that tomorrow.

**Comment by Vysp3r** [comment] 2022-12-12 13:34
I think I may have found the problem, but I'm really not sure. Would you guys be inclined to test it from source on your system since I can't reproduce? I will create a branch just for this issue until you guys says it's resolved.

**Comment by yochananmarqos** [comment] 2022-12-12 15:15
Sure.

**Comment by Vysp3r** [comment] 2022-12-13 19:07
If you click on the info button for the tool that shows up as a dot, what path does it returns?

**Comment by Newbytee** [comment] 2022-12-13 19:13
Is this what you want: ![image](https://user-images.githubusercontent.com/4428753/207424235-1b31cb91-488e-4825-a4ec-03b92ddb85d5.png)

**Comment by Vysp3r** [comment] 2022-12-13 19:18
Yep, thanks

**Comment by Newbytee** [comment] 2022-12-13 19:21
I installed Boxtron now as a test and it was named "..":
![image](https://user-images.githubusercontent.com/4428753/207425463-6aa752c2-27ea-4702-a1c1-ba6022c9204c.png)

**Comment by Vysp3r** [comment] 2022-12-13 19:22
Okay, but for you does Lutris and Lutris DXVK works correctly too like @yochananmarqos or not?

**Comment by Newbytee** [comment] 2022-12-13 19:22
I don't use Lutris, so I'm not sure.

**Comment by Newbytee** [comment] 2022-12-13 19:23
Issue is reproducible with Lutris:

![image](https://user-images.githubusercontent.com/4428753/207425908-1669ee88-5826-4d65-8378-7fb2393751d4.png)

**Comment by Vysp3r** [comment] 2022-12-13 19:24
Okay, so it's more random then I thought since it's working for @yochananmarqos

**Comment by Vysp3r** [comment] 2022-12-13 19:24
I'll take a look into that right now

**Comment by Vysp3r** [comment] 2022-12-13 19:38
I got my application to crash after installing tools multiple times in a row. The naming was weird too after 3 installation. I might be on to something.

**Comment by Vysp3r** [comment] 2022-12-13 20:00
> Issue is reproducible with Lutris: ![image](https://user-images.githubusercontent.com/4428753/207425908-1669ee88-5826-4d65-8378-7fb2393751d4.png)

Since you can see other installed tools correctly, I guess it's not the way my program shows the tools that's the problem, but the thing that download and extract a downloaded tool.

**Comment by Vysp3r** [comment] 2022-12-13 20:14
It would be nice if you guys could test this possible fix too! [LINK TO SOURCE](https://github.com/Vysp3r/ProtonPlus/tree/33-bug-ge-proton7-42-is-displayed-with-the-name-when-installed-to-steam-flatpak)

**Comment by Newbytee** [comment] 2022-12-13 20:50
Which one should I test? I would also like to note that this bug potentially can result in data loss. I tried removing the "." tool, and this resulted in all tools being removed from the Lutris launcher, not just the one I requested to remove.

**Comment by yochananmarqos** [comment] 2022-12-13 20:50
@Vysp3r No, that does not make any difference. 

Proton GE is not detected at all, no matter if it's already exists or if download with this program.

Lutris and Lutris DXVK versions are detected.

The paths are all correct.

All show as `..` no matter what.

![Screenshot from 2022-12-13 13-47-14](https://user-images.githubusercontent.com/5437803/207440265-778b3d07-63b4-4f41-8b97-6b3df1625b16.png)

![Screenshot from 2022-12-13 13-47-21](https://user-images.githubusercontent.com/5437803/207440373-e378380d-aff0-4888-b811-af751b17ee3f.png)

![Screenshot from 2022-12-13 13-47-25](https://user-images.githubusercontent.com/5437803/207440391-c4797e2f-b1bb-40fa-be95-e1aec3d7515c.png)

**Comment by Vysp3r** [comment] 2022-12-13 20:52
> Which one should I test? I would also like to note that this bug potentially can result in data loss. I tried removing the "." tool, and this resulted in all tools being removed from the Lutris launcher, not just the one I requested to remove.

That's normal because it deletes with the tool name. So if the tool name is a dot well it will delete everything since a dot is the current directory

**Comment by Newbytee** [comment] 2022-12-13 20:53
> > Which one should I test? I would also like to note that this bug potentially can result in data loss. I tried removing the "." tool, and this resulted in all tools being removed from the Lutris launcher, not just the one I requested to remove.
> 
> That's normal because it deletes with the tool name. So if the tool name is a dot well it will delete everything since a dot is the current directory

Yeah, I get that. But I don't think it's very good behaviour.

**Comment by Vysp3r** [comment] 2022-12-13 20:54
> > > Which one should I test? I would also like to note that this bug potentially can result in data loss. I tried removing the "." tool, and this resulted in all tools being removed from the Lutris launcher, not just the one I requested to remove.
> > 
> > 
> > That's normal because it deletes with the tool name. So if the tool name is a dot well it will delete everything since a dot is the current directory
> 
> Yeah, I get that. But I don't think it's very good behaviour.

I can always add a verification to make sure that if a tool is named dot or a special char like that you cannot delete it. That can be done really easily.

**Comment by Vysp3r** [comment] 2022-12-13 20:57
I added that to my to-do list, I will include that for the next update.

**Comment by Vysp3r** [comment] 2022-12-13 21:00
@yochananmarqos I updated [this branch](https://github.com/Vysp3r/ProtonPlus/tree/33-bug-ge-proton7-42-is-displayed-with-the-name-when-installed-to-steam-flatpak) again, could you please try it.

**Comment by yochananmarqos** [comment] 2022-12-13 21:07
No difference. 

Just in case you hadn't noticed, I had edited my last post.

**Comment by Vysp3r** [comment] 2022-12-13 21:10
Oh then I think it's the way I list the tools, it may think that . and .. is a tool. I have a filter on that, but maybe it's not reliable. I'll take a look into that.

**Comment by Vysp3r** [comment] 2022-12-13 21:15
@yochananmarqos I updated [this branch](https://github.com/Vysp3r/ProtonPlus/tree/33-bug-ge-proton7-42-is-displayed-with-the-name-when-installed-to-steam-flatpak)  again, could you please try it. I added a filter on '.' and '..' to prevent them showing up.

**Comment by yochananmarqos** [comment] 2022-12-13 21:19
Well, now the `..` doesn't show up. Other than that, there is no difference.

![Screenshot from 2022-12-13 14-17-37](https://user-images.githubusercontent.com/5437803/207445731-4363178a-ac28-4272-be2c-22d3ec2fe570.png)


FYI, I also have lutris GE Proton present, but it isn't detected.

`~/.local/share/lutris/runners/wine/lutris-GE-ProtonX-XX-x86_64`

**Comment by Vysp3r** [comment] 2022-12-13 21:22
Okay so Lutris doesn't show everything there's suppose to be?

**Comment by yochananmarqos** [comment] 2022-12-13 21:30
Sure, but that's only part of the problem. GE-Proton isn't being detected as installed no matter if it's the Steam or Lutris version.

**Comment by Vysp3r** [comment] 2022-12-13 21:33
Okay, but if you go check where the tools are installed, do you see them? Like do you see a folder named . with the stuff from Proton-GE or there's a folder named Proton-GE7-41 or whatever, but it my program just does not see it?

**Comment by yochananmarqos** [comment] 2022-12-13 21:41
Yes. I've already mentioned that multiple times.

**Comment by Vysp3r** [comment] 2022-12-13 22:49
@yochananmarqos I updated [this branch](https://github.com/Vysp3r/ProtonPlus/tree/33-bug-ge-proton7-42-is-displayed-with-the-name-when-installed-to-steam-flatpak)  again, could you please try it.

**Comment by yochananmarqos** [comment] 2022-12-13 23:22
Yes, that did the trick! Thanks. I'd say tag a new release.

**Comment by Vysp3r** [comment] 2022-12-13 23:29
Yep, I just have another pending issue which I want to fix first before the next update.

**Comment by yochananmarqos** [comment] 2022-12-13 23:34
...and while we're at it: #39 :wink:

**Comment by Vysp3r** [comment] 2022-12-13 23:56
Closing since fixed in https://github.com/Vysp3r/ProtonPlus/commit/bca7516600c2812b3b679a8289ccb656ff9d9154

**Closed by Vysp3r** 2022-12-13 23:56 UTC
Labels: bug
